### ISSUE TITLE
Feature Request : Lottery

### ISSUE THREAD

**Issue by gg-vara** [Amphaal/nightworkers#30]
On mets en vente des tickets de lotterie à 10000 $AIDS
Chaque joueur aura une chance proportionnelle à son nombre de tickets par rapport au nombre de tickets de l’ensemble des participants
Le jackpot est constitué de 50% de la somme totale des $AIDS mis en jeu (les autres 50% sont brulés)
Exemple : j’achète 1 ticket et 99 autres achètent un ticket, je détiens donc 1% de la mise globale de 100000000 $AIDS.
J’ai donc 1 % de chance de gagner 50000000 $AIDS et les 50000000 autres $AIDS sont brulés.

**Comment by gg-vara** [comment]
When to start ? When to end ? When to pick winner ?

**Comment by LimeSku** [comment]
On empêche un user de bet + de la moitié du jackpot (à l'instant t) à lui seul, pour ne pas le mettre en perte si les autres users ne suivent pas ou no care ?

**Comment by gg-vara** [comment]
> On empêche un user de bet + de la moitié du jackpot (à l'instant t) à lui seul, pour ne pas le mettre en perte si les autres users ne suivent pas ou no care ?

Bonne idée, à demander confirmation dans #whitelist
